- name: varibales from files
  hosts: local
  connection: local
  vars:
   - course.yaml
  tasks:
  - name: print the variables
    ansible.builtin.debug:
     msg: "Cousrse {{ COURSE }} ,COMPLETATION {{ DURATION }}"