- name: varibales
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter your course name 
  - name: DURATION
    prompt: please enter duartion of the course
  tasks:
  - name: print the variables
    ansible.builtin.debug:
     msg: "Cousrse {{ COURSE }} ,COMPLETATION {{ DURATION }}"