- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    # GREET: "PLAY"
  # vars_files:
  #   - course.yaml
  # vars_prompt:
  #  - name: GREET
  #    prompt: Enter the value
  #    private: false
  tasks:
  - name: print the variable
    # vars:
    #  GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

#1.args
#2.local
#3.file
#4.prompt
#5.global
