- name: varibales
  hosts: local
  connection: local
  vars:
   COURSE: "DevOps with AWS"
   DURATION: 120HRS
  tasks:
  - name: print the variables
    ansible.builtin.debug:
     msg: "Cousrse {{ COURSE }} ,COMPLETATION {{ DURATION }}"